#include <SDL2/begin_code.h> 
#include <SDL2/close_code.h> 
#include <SDL2/SDL.h> 
#include <SDL2/SDL_assert.h> 
#include <SDL2/SDL_atomic.h> 
#include <SDL2/SDL_audio.h> 
#include <SDL2/SDL_bits.h> 
#include <SDL2/SDL_blendmode.h> 
#include <SDL2/SDL_clipboard.h> 
#include <SDL2/SDL_config.h> 
#include <SDL2/SDL_config_android.h> 
#include <SDL2/SDL_config_iphoneos.h> 
//#include <SDL2/SDL_config_macosx.h> 
#include <SDL2/SDL_config_minimal.h> 
#include <SDL2/SDL_config_os2.h> 
#include <SDL2/SDL_config_pandora.h> 
#include <SDL2/SDL_config_ps4.h> 
#include <SDL2/SDL_config_psp.h> 
//#include <SDL2/SDL_config_windows.h> 
//#include <SDL2/SDL_config_winrt.h> 
#include <SDL2/SDL_config_wiz.h> 
#include <SDL2/SDL_copying.h> 
#include <SDL2/SDL_cpuinfo.h> 
#include <SDL2/SDL_egl.h> 
#include <SDL2/SDL_endian.h> 
#include <SDL2/SDL_error.h> 
#include <SDL2/SDL_events.h> 
#include <SDL2/SDL_filesystem.h> 
#include <SDL2/SDL_gamecontroller.h> 
#include <SDL2/SDL_gesture.h> 
#include <SDL2/SDL_haptic.h> 
#include <SDL2/SDL_hints.h> 
#include <SDL2/SDL_image.h> 
#include <SDL2/SDL_joystick.h> 
#include <SDL2/SDL_keyboard.h> 
#include <SDL2/SDL_keycode.h> 
#include <SDL2/SDL_loadso.h> 
#include <SDL2/SDL_log.h> 
#include <SDL2/SDL_main.h> 
#include <SDL2/SDL_messagebox.h> 
#include <SDL2/SDL_mouse.h> 
#include <SDL2/SDL_mutex.h> 
#include <SDL2/SDL_name.h> 
#include <SDL2/SDL_opengl.h> 
#include <SDL2/SDL_opengl_glext.h> 
//#include <SDL2/SDL_opengles.h> 
#include <SDL2/SDL_opengles2.h> 
#include <SDL2/SDL_opengles2_gl2.h> 
#include <SDL2/SDL_opengles2_gl2ext.h> 
#include <SDL2/SDL_opengles2_gl2platform.h> 
#include <SDL2/SDL_opengles2_khrplatform.h> 
#include <SDL2/SDL_pixels.h> 
#include <SDL2/SDL_platform.h> 
#include <SDL2/SDL_power.h> 
#include <SDL2/SDL_quit.h> 
#include <SDL2/SDL_rect.h> 
#include <SDL2/SDL_render.h> 
#include <SDL2/SDL_revision.h> 
#include <SDL2/SDL_rwops.h> 
#include <SDL2/SDL_scancode.h> 
#include <SDL2/SDL_sensor.h> 
#include <SDL2/SDL_shape.h> 
#include <SDL2/SDL_stdinc.h> 
#include <SDL2/SDL_surface.h> 
#include <SDL2/SDL_system.h> 
//#include <SDL2/SDL_syswm.h> 
#include <SDL2/SDL_test.h> 
#include <SDL2/SDL_test_assert.h> 
#include <SDL2/SDL_test_common.h> 
#include <SDL2/SDL_test_compare.h> 
#include <SDL2/SDL_test_crc32.h> 
#include <SDL2/SDL_test_font.h> 
#include <SDL2/SDL_test_fuzzer.h> 
#include <SDL2/SDL_test_harness.h> 
#include <SDL2/SDL_test_images.h> 
#include <SDL2/SDL_test_log.h> 
#include <SDL2/SDL_test_md5.h> 
#include <SDL2/SDL_test_memory.h> 
#include <SDL2/SDL_test_random.h> 
#include <SDL2/SDL_thread.h> 
#include <SDL2/SDL_timer.h> 
#include <SDL2/SDL_touch.h> 
#include <SDL2/SDL_ttf.h> 
#include <SDL2/SDL_types.h> 
#include <SDL2/SDL_version.h> 
#include <SDL2/SDL_video.h> 
#include <SDL2/SDL_vulkan.h>
#include "io.h"
#include "mono.h"


void NotImplemented(){
    klog("Internal Not Implemented Method Called");
    exit(1);
}

void add_call(const char* Path, void* method){
    //klogf("Adding Internal Call: %s", Path);
    mono_add_internal_call(Path, method);
}

void SetSDLInternals(){
    add_call("SDL2.SDL::INTERNAL_SDL_RWFromFile", NotImplemented);
    add_call("SDL2.SDL::INTERNAL_SDL_GetPlatform", NotImplemented);
    add_call("SDL2.SDL::INTERNAL_SDL_GetHint", NotImplemented);
    add_call("SDL2.SDL::INTERNAL_SDL_SetHint", NotImplemented);
    add_call("SDL2.SDL::INTERNAL_SDL_SetHintWithPriority", NotImplemented);
    add_call("SDL2.SDL::INTERNAL_SDL_GetHintBoolean", SDL_GetHintBoolean);
    add_call("SDL2.SDL::INTERNAL_SDL_GetError", SDL_GetError);
    add_call("SDL2.SDL::INTERNAL_SDL_SetError", SDL_SetError);
    add_call("SDL2.SDL::INTERNAL_SDL_Log", SDL_Log);
    add_call("SDL2.SDL::INTERNAL_SDL_LogVerbose", SDL_LogVerbose);
    add_call("SDL2.SDL::INTERNAL_SDL_LogDebug", SDL_LogDebug);
    add_call("SDL2.SDL::INTERNAL_SDL_LogInfo", SDL_LogInfo);
    add_call("SDL2.SDL::INTERNAL_SDL_LogWarn", SDL_LogWarn);
    add_call("SDL2.SDL::INTERNAL_SDL_LogError", SDL_LogError);
    add_call("SDL2.SDL::INTERNAL_SDL_LogCritical", SDL_LogCritical);
    add_call("SDL2.SDL::INTERNAL_SDL_LogMessage", SDL_LogMessage);
    add_call("SDL2.SDL::INTERNAL_SDL_LogMessageV", SDL_LogMessageV);
    add_call("SDL2.SDL::INTERNAL_SDL_ShowSimpleMessageBox", SDL_ShowSimpleMessageBox);
    add_call("SDL2.SDL::INTERNAL_SDL_GetRevision", SDL_GetRevision);
    add_call("SDL2.SDL::INTERNAL_SDL_CreateWindow", SDL_CreateWindow);
    add_call("SDL2.SDL::INTERNAL_SDL_GetCurrentVideoDriver", SDL_GetCurrentVideoDriver);
    add_call("SDL2.SDL::INTERNAL_SDL_GetDisplayName", SDL_GetDisplayName);
    add_call("SDL2.SDL::INTERNAL_SDL_GetVideoDriver", SDL_GetVideoDriver);
    add_call("SDL2.SDL::INTERNAL_SDL_GetWindowData", SDL_GetWindowData);
    add_call("SDL2.SDL::INTERNAL_SDL_GetWindowTitle", SDL_GetWindowTitle);
    add_call("SDL2.SDL::INTERNAL_SDL_GL_GetProcAddress", SDL_GL_GetProcAddress);
    add_call("SDL2.SDL::INTERNAL_SDL_GL_LoadLibrary", SDL_GL_LoadLibrary);
    add_call("SDL2.SDL::INTERNAL_SDL_GL_ExtensionSupported", SDL_GL_ExtensionSupported);
    add_call("SDL2.SDL::INTERNAL_SDL_SetWindowData", SDL_SetWindowData);
    add_call("SDL2.SDL::INTERNAL_SDL_SetWindowTitle", SDL_SetWindowTitle);
    add_call("SDL2.SDL::INTERNAL_SDL_VideoInit", SDL_VideoInit);
    add_call("SDL2.SDL::INTERNAL_SDL_Vulkan_LoadLibrary", SDL_Vulkan_LoadLibrary);
    add_call("SDL2.SDL::INTERNAL_SDL_GetPixelFormatName", SDL_GetPixelFormatName);
    add_call("SDL2.SDL::SDL_BlitSurface", SDL_UpperBlit);
    add_call("SDL2.SDL::SDL_BlitSurface", SDL_UpperBlit);
    add_call("SDL2.SDL::SDL_BlitSurface", SDL_UpperBlit);
    add_call("SDL2.SDL::SDL_BlitSurface", SDL_UpperBlit);
    add_call("SDL2.SDL::SDL_BlitScaled", SDL_UpperBlitScaled);
    add_call("SDL2.SDL::SDL_BlitScaled", SDL_UpperBlitScaled);
    add_call("SDL2.SDL::SDL_BlitScaled", SDL_UpperBlitScaled);
    add_call("SDL2.SDL::SDL_BlitScaled", SDL_UpperBlitScaled);
    add_call("SDL2.SDL::INTERNAL_SDL_LoadBMP_RW", SDL_LoadBMP_RW);
    add_call("SDL2.SDL::INTERNAL_SDL_SaveBMP_RW", SDL_SaveBMP_RW);
    add_call("SDL2.SDL::INTERNAL_SDL_GetClipboardText", SDL_GetClipboardText);
    add_call("SDL2.SDL::INTERNAL_SDL_SetClipboardText", SDL_SetClipboardText);
    add_call("SDL2.SDL::INTERNAL_SDL_GetScancodeName", SDL_GetScancodeName);
    add_call("SDL2.SDL::INTERNAL_SDL_GetScancodeFromName", SDL_GetScancodeFromName);
    add_call("SDL2.SDL::INTERNAL_SDL_GetKeyName", SDL_GetKeyName);
    add_call("SDL2.SDL::INTERNAL_SDL_GetKeyFromName", SDL_GetKeyFromName);
    add_call("SDL2.SDL::INTERNAL_SDL_JoystickName", SDL_JoystickName);
    add_call("SDL2.SDL::INTERNAL_SDL_JoystickNameForIndex", SDL_JoystickNameForIndex);
    add_call("SDL2.SDL::INTERNAL_SDL_JoystickGetGUIDFromString", SDL_JoystickGetGUIDFromString);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerAddMapping", SDL_GameControllerAddMapping);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerMappingForIndex", SDL_GameControllerMappingForIndex);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerAddMappingsFromRW", SDL_GameControllerAddMappingsFromRW);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerMappingForGUID", SDL_GameControllerMappingForGUID);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerMapping", SDL_GameControllerMapping);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerNameForIndex", SDL_GameControllerNameForIndex);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerMappingForDeviceIndex", SDL_GameControllerMappingForDeviceIndex);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerName", SDL_GameControllerName);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerGetAxisFromString", SDL_GameControllerGetAxisFromString);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerGetStringForAxis", SDL_GameControllerGetStringForAxis);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerGetBindForAxis", SDL_GameControllerGetBindForAxis);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerGetButtonFromString", SDL_GameControllerGetButtonFromString);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerGetStringForButton", SDL_GameControllerGetStringForButton);
    add_call("SDL2.SDL::INTERNAL_SDL_GameControllerGetBindForButton", SDL_GameControllerGetBindForButton);
    add_call("SDL2.SDL::INTERNAL_SDL_HapticName", SDL_HapticName);
    add_call("SDL2.SDL::INTERNAL_SDL_SensorGetDeviceName", SDL_SensorGetDeviceName);
    add_call("SDL2.SDL::INTERNAL_SDL_SensorGetName", SDL_SensorGetName);
    add_call("SDL2.SDL::INTERNAL_SDL_AudioInit", SDL_AudioInit);
    add_call("SDL2.SDL::INTERNAL_SDL_GetAudioDeviceName", SDL_GetAudioDeviceName);
    add_call("SDL2.SDL::INTERNAL_SDL_GetAudioDriver", SDL_GetAudioDriver);
    add_call("SDL2.SDL::INTERNAL_SDL_GetCurrentAudioDriver", SDL_GetCurrentAudioDriver);
    add_call("SDL2.SDL::INTERNAL_SDL_LoadWAV_RW", SDL_LoadWAV_RW);
    add_call("SDL2.SDL::INTERNAL_SDL_OpenAudioDevice", SDL_OpenAudioDevice);
    add_call("SDL2.SDL::INTERNAL_SDL_AndroidGetInternalStoragePath", NotImplemented);
    add_call("SDL2.SDL::INTERNAL_SDL_GetBasePath", SDL_GetBasePath);
    add_call("SDL2.SDL::INTERNAL_SDL_GetPrefPath", SDL_GetPrefPath);
    
    add_call("SDL2.SDL::SDL_malloc", SDL_malloc);
    add_call("SDL2.SDL::SDL_free", SDL_free);
    add_call("SDL2.SDL::SDL_RWFromMem", SDL_RWFromMem);
    add_call("SDL2.SDL::SDL_SetMainReady", SDL_SetMainReady);
    add_call("SDL2.SDL::SDL_WinRTRunApp", NotImplemented);
    add_call("SDL2.SDL::SDL_Init", SDL_Init);
    add_call("SDL2.SDL::SDL_InitSubSystem", SDL_InitSubSystem);
    add_call("SDL2.SDL::SDL_Quit", SDL_Quit);
    add_call("SDL2.SDL::SDL_QuitSubSystem", SDL_QuitSubSystem);
    add_call("SDL2.SDL::SDL_WasInit", SDL_WasInit);
    add_call("SDL2.SDL::SDL_ClearHints", SDL_ClearHints);
    add_call("SDL2.SDL::SDL_ClearError", SDL_ClearError);
    add_call("SDL2.SDL::SDL_LogGetPriority", SDL_LogGetPriority);
    add_call("SDL2.SDL::SDL_LogSetPriority", SDL_LogSetPriority);
    add_call("SDL2.SDL::SDL_LogSetAllPriority", SDL_LogSetAllPriority);
    add_call("SDL2.SDL::SDL_LogResetPriorities", SDL_LogResetPriorities);
    add_call("SDL2.SDL::SDL_LogGetOutputFunction", SDL_LogGetOutputFunction);
    add_call("SDL2.SDL::SDL_LogSetOutputFunction", SDL_LogSetOutputFunction);
    add_call("SDL2.SDL::SDL_GetVersion", SDL_GetVersion);
    add_call("SDL2.SDL::SDL_GetRevisionNumber", SDL_GetRevisionNumber);
    add_call("SDL2.SDL::SDL_CreateWindowAndRenderer", SDL_CreateWindowAndRenderer);
    add_call("SDL2.SDL::SDL_CreateWindowFrom", SDL_CreateWindowFrom);
    add_call("SDL2.SDL::SDL_DestroyWindow", SDL_DestroyWindow);
    add_call("SDL2.SDL::SDL_DisableScreenSaver", SDL_DisableScreenSaver);
    add_call("SDL2.SDL::SDL_EnableScreenSaver", SDL_EnableScreenSaver);
    add_call("SDL2.SDL::SDL_GetClosestDisplayMode", SDL_GetClosestDisplayMode);
    add_call("SDL2.SDL::SDL_GetCurrentDisplayMode", SDL_GetCurrentDisplayMode);
    add_call("SDL2.SDL::SDL_GetDesktopDisplayMode", SDL_GetDesktopDisplayMode);
    add_call("SDL2.SDL::SDL_GetDisplayBounds", SDL_GetDisplayBounds);
    add_call("SDL2.SDL::SDL_GetDisplayDPI", SDL_GetDisplayDPI);
    add_call("SDL2.SDL::SDL_GetDisplayOrientation", SDL_GetDisplayOrientation);
    add_call("SDL2.SDL::SDL_GetDisplayMode", SDL_GetDisplayMode);
    add_call("SDL2.SDL::SDL_GetDisplayUsableBounds", SDL_GetDisplayUsableBounds);
    add_call("SDL2.SDL::SDL_GetNumDisplayModes", SDL_GetNumDisplayModes);
    add_call("SDL2.SDL::SDL_GetNumVideoDisplays", SDL_GetNumVideoDisplays);
    add_call("SDL2.SDL::SDL_GetNumVideoDrivers", SDL_GetNumVideoDrivers);
    add_call("SDL2.SDL::SDL_GetWindowBrightness", SDL_GetWindowBrightness);
    add_call("SDL2.SDL::SDL_SetWindowOpacity", SDL_SetWindowOpacity);
    add_call("SDL2.SDL::SDL_GetWindowOpacity", SDL_GetWindowOpacity);
    add_call("SDL2.SDL::SDL_SetWindowModalFor", SDL_SetWindowModalFor);
    add_call("SDL2.SDL::SDL_SetWindowInputFocus", SDL_SetWindowInputFocus);
    add_call("SDL2.SDL::SDL_GetWindowDisplayIndex", SDL_GetWindowDisplayIndex);
    add_call("SDL2.SDL::SDL_GetWindowDisplayMode", SDL_GetWindowDisplayMode);
    add_call("SDL2.SDL::SDL_GetWindowFlags", SDL_GetWindowFlags);
    add_call("SDL2.SDL::SDL_GetWindowFromID", SDL_GetWindowFromID);
    add_call("SDL2.SDL::SDL_GetWindowGrab", SDL_GetWindowGrab);
    add_call("SDL2.SDL::SDL_GetWindowID", SDL_GetWindowID);
    add_call("SDL2.SDL::SDL_GetWindowPixelFormat", SDL_GetWindowPixelFormat);
    add_call("SDL2.SDL::SDL_GetWindowMaximumSize", SDL_GetWindowMaximumSize);
    add_call("SDL2.SDL::SDL_GetWindowMinimumSize", SDL_GetWindowMinimumSize);
    add_call("SDL2.SDL::SDL_GetWindowPosition", SDL_GetWindowPosition);
    add_call("SDL2.SDL::SDL_GetWindowSize", SDL_GetWindowSize);
    add_call("SDL2.SDL::SDL_GetWindowSurface", SDL_GetWindowSurface);
    add_call("SDL2.SDL::SDL_GL_BindTexture", SDL_GL_BindTexture);
    add_call("SDL2.SDL::SDL_GL_CreateContext", SDL_GL_CreateContext);
    add_call("SDL2.SDL::SDL_GL_DeleteContext", SDL_GL_DeleteContext);
    add_call("SDL2.SDL::SDL_GL_GetProcAddress", SDL_GL_GetProcAddress);
    add_call("SDL2.SDL::SDL_GL_UnloadLibrary", SDL_GL_UnloadLibrary);
    add_call("SDL2.SDL::SDL_GL_ResetAttributes", SDL_GL_ResetAttributes);
    add_call("SDL2.SDL::SDL_GL_GetAttribute", SDL_GL_GetAttribute);
    add_call("SDL2.SDL::SDL_GL_GetSwapInterval", SDL_GL_GetSwapInterval);
    add_call("SDL2.SDL::SDL_GL_MakeCurrent", SDL_GL_MakeCurrent);
    add_call("SDL2.SDL::SDL_GL_GetCurrentWindow", SDL_GL_GetCurrentWindow);
    add_call("SDL2.SDL::SDL_GL_GetCurrentContext", SDL_GL_GetCurrentContext);
    add_call("SDL2.SDL::SDL_GL_GetDrawableSize", SDL_GL_GetDrawableSize);
    add_call("SDL2.SDL::SDL_GL_SetAttribute", SDL_GL_SetAttribute);
    add_call("SDL2.SDL::SDL_GL_SetSwapInterval", SDL_GL_SetSwapInterval);
    add_call("SDL2.SDL::SDL_GL_SwapWindow", SDL_GL_SwapWindow);
    add_call("SDL2.SDL::SDL_GL_UnbindTexture", SDL_GL_UnbindTexture);
    add_call("SDL2.SDL::SDL_HideWindow", SDL_HideWindow);
    add_call("SDL2.SDL::SDL_IsScreenSaverEnabled", SDL_IsScreenSaverEnabled);
    add_call("SDL2.SDL::SDL_MaximizeWindow", SDL_MaximizeWindow);
    add_call("SDL2.SDL::SDL_MinimizeWindow", SDL_MinimizeWindow);
    add_call("SDL2.SDL::SDL_RaiseWindow", SDL_RaiseWindow);
    add_call("SDL2.SDL::SDL_RestoreWindow", SDL_RestoreWindow);
    add_call("SDL2.SDL::SDL_SetWindowBrightness", SDL_SetWindowBrightness);
    add_call("SDL2.SDL::SDL_SetWindowDisplayMode", SDL_SetWindowDisplayMode);
    add_call("SDL2.SDL::SDL_SetWindowFullscreen", SDL_SetWindowFullscreen);
    add_call("SDL2.SDL::SDL_SetWindowGrab", SDL_SetWindowGrab);
    add_call("SDL2.SDL::SDL_SetWindowIcon", SDL_SetWindowIcon);
    add_call("SDL2.SDL::SDL_SetWindowMaximumSize", SDL_SetWindowMaximumSize);
    add_call("SDL2.SDL::SDL_SetWindowMinimumSize", SDL_SetWindowMinimumSize);
    add_call("SDL2.SDL::SDL_SetWindowPosition", SDL_SetWindowPosition);
    add_call("SDL2.SDL::SDL_SetWindowSize", SDL_SetWindowSize);
    add_call("SDL2.SDL::SDL_SetWindowBordered", SDL_SetWindowBordered);
    add_call("SDL2.SDL::SDL_GetWindowBordersSize", SDL_GetWindowBordersSize);
    add_call("SDL2.SDL::SDL_SetWindowResizable", SDL_SetWindowResizable);
    add_call("SDL2.SDL::SDL_ShowWindow", SDL_ShowWindow);
    add_call("SDL2.SDL::SDL_UpdateWindowSurface", SDL_UpdateWindowSurface);
    add_call("SDL2.SDL::SDL_UpdateWindowSurfaceRects", SDL_UpdateWindowSurfaceRects);
    add_call("SDL2.SDL::SDL_VideoQuit", SDL_VideoQuit);
    add_call("SDL2.SDL::SDL_SetWindowHitTest", SDL_SetWindowHitTest);
    add_call("SDL2.SDL::SDL_GetGrabbedWindow", SDL_GetGrabbedWindow);
    add_call("SDL2.SDL::SDL_ComposeCustomBlendMode", SDL_ComposeCustomBlendMode);
    add_call("SDL2.SDL::SDL_Vulkan_GetVkGetInstanceProcAddr", SDL_Vulkan_GetVkGetInstanceProcAddr);
    add_call("SDL2.SDL::SDL_Vulkan_UnloadLibrary", SDL_Vulkan_UnloadLibrary);
    add_call("SDL2.SDL::SDL_Vulkan_GetInstanceExtensions", SDL_Vulkan_GetInstanceExtensions);
    add_call("SDL2.SDL::SDL_Vulkan_CreateSurface", SDL_Vulkan_CreateSurface);
    add_call("SDL2.SDL::SDL_Vulkan_GetDrawableSize", SDL_Vulkan_GetDrawableSize);
    add_call("SDL2.SDL::SDL_CreateRenderer", SDL_CreateRenderer);
    add_call("SDL2.SDL::SDL_CreateSoftwareRenderer", SDL_CreateSoftwareRenderer);
    add_call("SDL2.SDL::SDL_CreateTexture", SDL_CreateTexture);
    add_call("SDL2.SDL::SDL_CreateTextureFromSurface", SDL_CreateTextureFromSurface);
    add_call("SDL2.SDL::SDL_DestroyRenderer", SDL_DestroyRenderer);
    add_call("SDL2.SDL::SDL_DestroyTexture", SDL_DestroyTexture);
    add_call("SDL2.SDL::SDL_GetNumRenderDrivers", SDL_GetNumRenderDrivers);
    add_call("SDL2.SDL::SDL_GetRenderDrawBlendMode", SDL_GetRenderDrawBlendMode);
    add_call("SDL2.SDL::SDL_GetRenderDrawColor", SDL_GetRenderDrawColor);
    add_call("SDL2.SDL::SDL_GetRenderDriverInfo", SDL_GetRenderDriverInfo);
    add_call("SDL2.SDL::SDL_GetRenderer", SDL_GetRenderer);
    add_call("SDL2.SDL::SDL_GetRendererInfo", SDL_GetRendererInfo);
    add_call("SDL2.SDL::SDL_GetRendererOutputSize", SDL_GetRendererOutputSize);
    add_call("SDL2.SDL::SDL_GetTextureAlphaMod", SDL_GetTextureAlphaMod);
    add_call("SDL2.SDL::SDL_GetTextureBlendMode", SDL_GetTextureBlendMode);
    add_call("SDL2.SDL::SDL_GetTextureColorMod", SDL_GetTextureColorMod);
    add_call("SDL2.SDL::SDL_LockTexture", SDL_LockTexture);
    add_call("SDL2.SDL::SDL_LockTexture", SDL_LockTexture);
    add_call("SDL2.SDL::SDL_QueryTexture", SDL_QueryTexture);
    add_call("SDL2.SDL::SDL_RenderClear", SDL_RenderClear);
    add_call("SDL2.SDL::SDL_RenderCopy", SDL_RenderCopy);
    add_call("SDL2.SDL::SDL_RenderCopy", SDL_RenderCopy);
    add_call("SDL2.SDL::SDL_RenderCopy", SDL_RenderCopy);
    add_call("SDL2.SDL::SDL_RenderCopy", SDL_RenderCopy);
    add_call("SDL2.SDL::SDL_RenderCopyEx", SDL_RenderCopyEx);
    add_call("SDL2.SDL::SDL_RenderCopyEx", SDL_RenderCopyEx);
    add_call("SDL2.SDL::SDL_RenderCopyEx", SDL_RenderCopyEx);
    add_call("SDL2.SDL::SDL_RenderCopyEx", SDL_RenderCopyEx);
    add_call("SDL2.SDL::SDL_RenderCopyEx", SDL_RenderCopyEx);
    add_call("SDL2.SDL::SDL_RenderCopyEx", SDL_RenderCopyEx);
    add_call("SDL2.SDL::SDL_RenderCopyEx", SDL_RenderCopyEx);
    add_call("SDL2.SDL::SDL_RenderCopyEx", SDL_RenderCopyEx);
    add_call("SDL2.SDL::SDL_RenderDrawLine", SDL_RenderDrawLine);
    add_call("SDL2.SDL::SDL_RenderDrawLines", SDL_RenderDrawLines);
    add_call("SDL2.SDL::SDL_RenderDrawPoint", SDL_RenderDrawPoint);
    add_call("SDL2.SDL::SDL_RenderDrawPoints", SDL_RenderDrawPoints);
    add_call("SDL2.SDL::SDL_RenderDrawRect", SDL_RenderDrawRect);
    add_call("SDL2.SDL::SDL_RenderDrawRect", SDL_RenderDrawRect);
    add_call("SDL2.SDL::SDL_RenderDrawRects", SDL_RenderDrawRects);
    add_call("SDL2.SDL::SDL_RenderFillRect", SDL_RenderFillRect);
    add_call("SDL2.SDL::SDL_RenderFillRect", SDL_RenderFillRect);
    add_call("SDL2.SDL::SDL_RenderFillRects", SDL_RenderFillRects);
    add_call("SDL2.SDL::SDL_RenderGetClipRect", SDL_RenderGetClipRect);
    add_call("SDL2.SDL::SDL_RenderGetLogicalSize", SDL_RenderGetLogicalSize);
    add_call("SDL2.SDL::SDL_RenderGetScale", SDL_RenderGetScale);
    add_call("SDL2.SDL::SDL_RenderGetViewport", SDL_RenderGetViewport);
    add_call("SDL2.SDL::SDL_RenderPresent", SDL_RenderPresent);
    add_call("SDL2.SDL::SDL_RenderReadPixels", SDL_RenderReadPixels);
    add_call("SDL2.SDL::SDL_RenderSetClipRect", SDL_RenderSetClipRect);
    add_call("SDL2.SDL::SDL_RenderSetClipRect", SDL_RenderSetClipRect);
    add_call("SDL2.SDL::SDL_RenderSetLogicalSize", SDL_RenderSetLogicalSize);
    add_call("SDL2.SDL::SDL_RenderSetScale", SDL_RenderSetScale);
    add_call("SDL2.SDL::SDL_RenderSetIntegerScale", SDL_RenderSetIntegerScale);
    add_call("SDL2.SDL::SDL_RenderSetViewport", SDL_RenderSetViewport);
    add_call("SDL2.SDL::SDL_SetRenderDrawBlendMode", SDL_SetRenderDrawBlendMode);
    add_call("SDL2.SDL::SDL_SetRenderDrawColor", SDL_SetRenderDrawColor);
    add_call("SDL2.SDL::SDL_SetRenderTarget", SDL_SetRenderTarget);
    add_call("SDL2.SDL::SDL_SetTextureAlphaMod", SDL_SetTextureAlphaMod);
    add_call("SDL2.SDL::SDL_SetTextureBlendMode", SDL_SetTextureBlendMode);
    add_call("SDL2.SDL::SDL_SetTextureColorMod", SDL_SetTextureColorMod);
    add_call("SDL2.SDL::SDL_UnlockTexture", SDL_UnlockTexture);
    add_call("SDL2.SDL::SDL_UpdateTexture", SDL_UpdateTexture);
    add_call("SDL2.SDL::SDL_UpdateTexture", SDL_UpdateTexture);
    add_call("SDL2.SDL::SDL_UpdateYUVTexture", SDL_UpdateYUVTexture);
    add_call("SDL2.SDL::SDL_RenderTargetSupported", SDL_RenderTargetSupported);
    add_call("SDL2.SDL::SDL_GetRenderTarget", SDL_GetRenderTarget);
    add_call("SDL2.SDL::SDL_RenderGetMetalLayer", SDL_RenderGetMetalLayer);
    add_call("SDL2.SDL::SDL_RenderGetMetalCommandEncoder", SDL_RenderGetMetalCommandEncoder);
    add_call("SDL2.SDL::SDL_RenderIsClipEnabled", SDL_RenderIsClipEnabled);
    add_call("SDL2.SDL::SDL_AllocFormat", SDL_AllocFormat);
    add_call("SDL2.SDL::SDL_AllocPalette", SDL_AllocPalette);
    add_call("SDL2.SDL::SDL_FreeFormat", SDL_FreeFormat);
    add_call("SDL2.SDL::SDL_FreePalette", SDL_FreePalette);
    add_call("SDL2.SDL::SDL_GetRGB", SDL_GetRGB);
    add_call("SDL2.SDL::SDL_GetRGBA", SDL_GetRGBA);
    add_call("SDL2.SDL::SDL_MapRGB", SDL_MapRGB);
    add_call("SDL2.SDL::SDL_MapRGBA", SDL_MapRGBA);
    add_call("SDL2.SDL::SDL_MasksToPixelFormatEnum", SDL_MasksToPixelFormatEnum);
    add_call("SDL2.SDL::SDL_PixelFormatEnumToMasks", SDL_PixelFormatEnumToMasks);
    add_call("SDL2.SDL::SDL_SetPaletteColors", SDL_SetPaletteColors);
    add_call("SDL2.SDL::SDL_SetPixelFormatPalette", SDL_SetPixelFormatPalette);
    add_call("SDL2.SDL::SDL_EnclosePoints", SDL_EnclosePoints);
    add_call("SDL2.SDL::SDL_HasIntersection", SDL_HasIntersection);
    add_call("SDL2.SDL::SDL_IntersectRect", SDL_IntersectRect);
    add_call("SDL2.SDL::SDL_IntersectRectAndLine", SDL_IntersectRectAndLine);
    add_call("SDL2.SDL::SDL_UnionRect", SDL_UnionRect);
    add_call("SDL2.SDL::SDL_ConvertPixels", SDL_ConvertPixels);
    add_call("SDL2.SDL::SDL_ConvertSurface", SDL_ConvertSurface);
    add_call("SDL2.SDL::SDL_ConvertSurfaceFormat", SDL_ConvertSurfaceFormat);
    add_call("SDL2.SDL::SDL_CreateRGBSurface", SDL_CreateRGBSurface);
    add_call("SDL2.SDL::SDL_CreateRGBSurfaceFrom", SDL_CreateRGBSurfaceFrom);
    add_call("SDL2.SDL::SDL_CreateRGBSurfaceWithFormat", SDL_CreateRGBSurfaceWithFormat);
    add_call("SDL2.SDL::SDL_CreateRGBSurfaceWithFormatFrom", SDL_CreateRGBSurfaceWithFormatFrom);
    add_call("SDL2.SDL::SDL_FillRect", SDL_FillRect);
    add_call("SDL2.SDL::SDL_FillRect", SDL_FillRect);
    add_call("SDL2.SDL::SDL_FillRects", SDL_FillRects);
    add_call("SDL2.SDL::SDL_FreeSurface", SDL_FreeSurface);
    add_call("SDL2.SDL::SDL_GetClipRect", SDL_GetClipRect);
    add_call("SDL2.SDL::SDL_HasColorKey", SDL_HasColorKey);
    add_call("SDL2.SDL::SDL_GetColorKey", SDL_GetColorKey);
    add_call("SDL2.SDL::SDL_GetSurfaceAlphaMod", SDL_GetSurfaceAlphaMod);
    add_call("SDL2.SDL::SDL_GetSurfaceBlendMode", SDL_GetSurfaceBlendMode);
    add_call("SDL2.SDL::SDL_GetSurfaceColorMod", SDL_GetSurfaceColorMod);
    add_call("SDL2.SDL::SDL_LockSurface", SDL_LockSurface);
    add_call("SDL2.SDL::SDL_LowerBlit", SDL_LowerBlit);
    add_call("SDL2.SDL::SDL_LowerBlitScaled", SDL_LowerBlitScaled);
    add_call("SDL2.SDL::SDL_SetClipRect", SDL_SetClipRect);
    add_call("SDL2.SDL::SDL_SetColorKey", SDL_SetColorKey);
    add_call("SDL2.SDL::SDL_SetSurfaceAlphaMod", SDL_SetSurfaceAlphaMod);
    add_call("SDL2.SDL::SDL_SetSurfaceBlendMode", SDL_SetSurfaceBlendMode);
    add_call("SDL2.SDL::SDL_SetSurfaceColorMod", SDL_SetSurfaceColorMod);
    add_call("SDL2.SDL::SDL_SetSurfacePalette", SDL_SetSurfacePalette);
    add_call("SDL2.SDL::SDL_SetSurfaceRLE", SDL_SetSurfaceRLE);
    add_call("SDL2.SDL::SDL_SoftStretch", SDL_SoftStretch);
    add_call("SDL2.SDL::SDL_UnlockSurface", SDL_UnlockSurface);
    add_call("SDL2.SDL::SDL_UpperBlit", SDL_UpperBlit);
    add_call("SDL2.SDL::SDL_UpperBlitScaled", SDL_UpperBlitScaled);
    add_call("SDL2.SDL::SDL_DuplicateSurface", SDL_DuplicateSurface);
    add_call("SDL2.SDL::SDL_HasClipboardText", SDL_HasClipboardText);
    add_call("SDL2.SDL::SDL_PumpEvents", SDL_PumpEvents);
    add_call("SDL2.SDL::SDL_PeepEvents", SDL_PeepEvents);
    add_call("SDL2.SDL::SDL_HasEvent", SDL_HasEvent);
    add_call("SDL2.SDL::SDL_HasEvents", SDL_HasEvents);
    add_call("SDL2.SDL::SDL_FlushEvent", SDL_FlushEvent);
    add_call("SDL2.SDL::SDL_FlushEvents", SDL_FlushEvents);
    add_call("SDL2.SDL::SDL_PollEvent", SDL_PollEvent);
    add_call("SDL2.SDL::SDL_WaitEvent", SDL_WaitEvent);
    add_call("SDL2.SDL::SDL_WaitEventTimeout", SDL_WaitEventTimeout);
    add_call("SDL2.SDL::SDL_PushEvent", SDL_PushEvent);
    add_call("SDL2.SDL::SDL_SetEventFilter", SDL_SetEventFilter);
    add_call("SDL2.SDL::SDL_GetEventFilter", SDL_GetEventFilter);
    add_call("SDL2.SDL::SDL_AddEventWatch", SDL_AddEventWatch);
    add_call("SDL2.SDL::SDL_DelEventWatch", SDL_DelEventWatch);
    add_call("SDL2.SDL::SDL_FilterEvents", SDL_FilterEvents);
    add_call("SDL2.SDL::SDL_EventState", SDL_EventState);
    add_call("SDL2.SDL::SDL_RegisterEvents", SDL_RegisterEvents);
    add_call("SDL2.SDL::SDL_GetKeyboardFocus", SDL_GetKeyboardFocus);
    add_call("SDL2.SDL::SDL_GetKeyboardState", SDL_GetKeyboardState);
    add_call("SDL2.SDL::SDL_GetModState", SDL_GetModState);
    add_call("SDL2.SDL::SDL_SetModState", SDL_SetModState);
    add_call("SDL2.SDL::SDL_GetKeyFromScancode", SDL_GetKeyFromScancode);
    add_call("SDL2.SDL::SDL_GetScancodeFromKey", SDL_GetScancodeFromKey);
    add_call("SDL2.SDL::SDL_StartTextInput", SDL_StartTextInput);
    add_call("SDL2.SDL::SDL_IsTextInputActive", SDL_IsTextInputActive);
    add_call("SDL2.SDL::SDL_StopTextInput", SDL_StopTextInput);
    add_call("SDL2.SDL::SDL_SetTextInputRect", SDL_SetTextInputRect);
    add_call("SDL2.SDL::SDL_HasScreenKeyboardSupport", SDL_HasScreenKeyboardSupport);
    add_call("SDL2.SDL::SDL_IsScreenKeyboardShown", SDL_IsScreenKeyboardShown);
    add_call("SDL2.SDL::SDL_GetMouseFocus", SDL_GetMouseFocus);
    add_call("SDL2.SDL::SDL_GetMouseState", SDL_GetMouseState);
    add_call("SDL2.SDL::SDL_GetMouseState", SDL_GetMouseState);
    add_call("SDL2.SDL::SDL_GetMouseState", SDL_GetMouseState);
    add_call("SDL2.SDL::SDL_GetMouseState", SDL_GetMouseState);
    add_call("SDL2.SDL::SDL_GetGlobalMouseState", SDL_GetGlobalMouseState);
    add_call("SDL2.SDL::SDL_GetGlobalMouseState", SDL_GetGlobalMouseState);
    add_call("SDL2.SDL::SDL_GetGlobalMouseState", SDL_GetGlobalMouseState);
    add_call("SDL2.SDL::SDL_GetGlobalMouseState", SDL_GetGlobalMouseState);
    add_call("SDL2.SDL::SDL_GetRelativeMouseState", SDL_GetRelativeMouseState);
    add_call("SDL2.SDL::SDL_WarpMouseInWindow", SDL_WarpMouseInWindow);
    add_call("SDL2.SDL::SDL_WarpMouseGlobal", SDL_WarpMouseGlobal);
    add_call("SDL2.SDL::SDL_SetRelativeMouseMode", SDL_SetRelativeMouseMode);
    add_call("SDL2.SDL::SDL_CaptureMouse", SDL_CaptureMouse);
    add_call("SDL2.SDL::SDL_GetRelativeMouseMode", SDL_GetRelativeMouseMode);
    add_call("SDL2.SDL::SDL_CreateCursor", SDL_CreateCursor);
    add_call("SDL2.SDL::SDL_CreateColorCursor", SDL_CreateColorCursor);
    add_call("SDL2.SDL::SDL_CreateSystemCursor", SDL_CreateSystemCursor);
    add_call("SDL2.SDL::SDL_SetCursor", SDL_SetCursor);
    add_call("SDL2.SDL::SDL_GetCursor", SDL_GetCursor);
    add_call("SDL2.SDL::SDL_FreeCursor", SDL_FreeCursor);
    add_call("SDL2.SDL::SDL_ShowCursor", SDL_ShowCursor);
    add_call("SDL2.SDL::SDL_GetNumTouchDevices", SDL_GetNumTouchDevices);
    add_call("SDL2.SDL::SDL_GetTouchDevice", SDL_GetTouchDevice);
    add_call("SDL2.SDL::SDL_GetNumTouchFingers", SDL_GetNumTouchFingers);
    add_call("SDL2.SDL::SDL_GetTouchFinger", SDL_GetTouchFinger);
    add_call("SDL2.SDL::SDL_JoystickRumble", SDL_JoystickRumble);
    add_call("SDL2.SDL::SDL_JoystickClose", SDL_JoystickClose);
    add_call("SDL2.SDL::SDL_JoystickEventState", SDL_JoystickEventState);
    add_call("SDL2.SDL::SDL_JoystickGetAxis", SDL_JoystickGetAxis);
    add_call("SDL2.SDL::SDL_JoystickGetAxisInitialState", SDL_JoystickGetAxisInitialState);
    add_call("SDL2.SDL::SDL_JoystickGetBall", SDL_JoystickGetBall);
    add_call("SDL2.SDL::SDL_JoystickGetButton", SDL_JoystickGetButton);
    add_call("SDL2.SDL::SDL_JoystickGetHat", SDL_JoystickGetHat);
    add_call("SDL2.SDL::SDL_JoystickNumAxes", SDL_JoystickNumAxes);
    add_call("SDL2.SDL::SDL_JoystickNumBalls", SDL_JoystickNumBalls);
    add_call("SDL2.SDL::SDL_JoystickNumButtons", SDL_JoystickNumButtons);
    add_call("SDL2.SDL::SDL_JoystickNumHats", SDL_JoystickNumHats);
    add_call("SDL2.SDL::SDL_JoystickOpen", SDL_JoystickOpen);
    add_call("SDL2.SDL::SDL_JoystickUpdate", SDL_JoystickUpdate);
    add_call("SDL2.SDL::SDL_NumJoysticks", SDL_NumJoysticks);
    add_call("SDL2.SDL::SDL_JoystickGetDeviceGUID", SDL_JoystickGetDeviceGUID);
    add_call("SDL2.SDL::SDL_JoystickGetGUID", SDL_JoystickGetGUID);
    add_call("SDL2.SDL::SDL_JoystickGetGUIDString", SDL_JoystickGetGUIDString);
    add_call("SDL2.SDL::SDL_JoystickGetDeviceVendor", SDL_JoystickGetDeviceVendor);
    add_call("SDL2.SDL::SDL_JoystickGetDeviceProduct", SDL_JoystickGetDeviceProduct);
    add_call("SDL2.SDL::SDL_JoystickGetDeviceProductVersion", SDL_JoystickGetDeviceProductVersion);
    add_call("SDL2.SDL::SDL_JoystickGetDeviceType", SDL_JoystickGetDeviceType);
    add_call("SDL2.SDL::SDL_JoystickGetDeviceInstanceID", SDL_JoystickGetDeviceInstanceID);
    add_call("SDL2.SDL::SDL_JoystickGetVendor", SDL_JoystickGetVendor);
    add_call("SDL2.SDL::SDL_JoystickGetProduct", SDL_JoystickGetProduct);
    add_call("SDL2.SDL::SDL_JoystickGetProductVersion", SDL_JoystickGetProductVersion);
    add_call("SDL2.SDL::SDL_JoystickGetType", SDL_JoystickGetType);
    add_call("SDL2.SDL::SDL_JoystickGetAttached", SDL_JoystickGetAttached);
    add_call("SDL2.SDL::SDL_JoystickInstanceID", SDL_JoystickInstanceID);
    add_call("SDL2.SDL::SDL_JoystickCurrentPowerLevel", SDL_JoystickCurrentPowerLevel);
    add_call("SDL2.SDL::SDL_JoystickFromInstanceID", SDL_JoystickFromInstanceID);
    add_call("SDL2.SDL::SDL_LockJoysticks", SDL_LockJoysticks);
    add_call("SDL2.SDL::SDL_UnlockJoysticks", SDL_UnlockJoysticks);
    add_call("SDL2.SDL::SDL_GameControllerNumMappings", SDL_GameControllerNumMappings);
    add_call("SDL2.SDL::SDL_IsGameController", SDL_IsGameController);
    add_call("SDL2.SDL::SDL_GameControllerOpen", SDL_GameControllerOpen);
    add_call("SDL2.SDL::SDL_GameControllerGetVendor", SDL_GameControllerGetVendor);
    add_call("SDL2.SDL::SDL_GameControllerGetProduct", SDL_GameControllerGetProduct);
    add_call("SDL2.SDL::SDL_GameControllerGetProductVersion", SDL_GameControllerGetProductVersion);
    add_call("SDL2.SDL::SDL_GameControllerGetAttached", SDL_GameControllerGetAttached);
    add_call("SDL2.SDL::SDL_GameControllerGetJoystick", SDL_GameControllerGetJoystick);
    add_call("SDL2.SDL::SDL_GameControllerEventState", SDL_GameControllerEventState);
    add_call("SDL2.SDL::SDL_GameControllerUpdate", SDL_GameControllerUpdate);
    add_call("SDL2.SDL::SDL_GameControllerGetAxis", SDL_GameControllerGetAxis);
    add_call("SDL2.SDL::SDL_GameControllerGetButton", SDL_GameControllerGetButton);
    add_call("SDL2.SDL::SDL_GameControllerRumble", SDL_GameControllerRumble);
    add_call("SDL2.SDL::SDL_GameControllerClose", SDL_GameControllerClose);
    add_call("SDL2.SDL::SDL_GameControllerFromInstanceID", SDL_GameControllerFromInstanceID);
    add_call("SDL2.SDL::SDL_HapticClose", SDL_HapticClose);
    add_call("SDL2.SDL::SDL_HapticDestroyEffect", SDL_HapticDestroyEffect);
    add_call("SDL2.SDL::SDL_HapticEffectSupported", SDL_HapticEffectSupported);
    add_call("SDL2.SDL::SDL_HapticGetEffectStatus", SDL_HapticGetEffectStatus);
    add_call("SDL2.SDL::SDL_HapticIndex", SDL_HapticIndex);
    add_call("SDL2.SDL::SDL_HapticNewEffect", SDL_HapticNewEffect);
    add_call("SDL2.SDL::SDL_HapticNumAxes", SDL_HapticNumAxes);
    add_call("SDL2.SDL::SDL_HapticNumEffects", SDL_HapticNumEffects);
    add_call("SDL2.SDL::SDL_HapticNumEffectsPlaying", SDL_HapticNumEffectsPlaying);
    add_call("SDL2.SDL::SDL_HapticOpen", SDL_HapticOpen);
    add_call("SDL2.SDL::SDL_HapticOpened", SDL_HapticOpened);
    add_call("SDL2.SDL::SDL_HapticOpenFromJoystick", SDL_HapticOpenFromJoystick);
    add_call("SDL2.SDL::SDL_HapticOpenFromMouse", SDL_HapticOpenFromMouse);
    add_call("SDL2.SDL::SDL_HapticPause", SDL_HapticPause);
    add_call("SDL2.SDL::SDL_HapticQuery", SDL_HapticQuery);
    add_call("SDL2.SDL::SDL_HapticRumbleInit", SDL_HapticRumbleInit);
    add_call("SDL2.SDL::SDL_HapticRumblePlay", SDL_HapticRumblePlay);
    add_call("SDL2.SDL::SDL_HapticRumbleStop", SDL_HapticRumbleStop);
    add_call("SDL2.SDL::SDL_HapticRumbleSupported", SDL_HapticRumbleSupported);
    add_call("SDL2.SDL::SDL_HapticRunEffect", SDL_HapticRunEffect);
    add_call("SDL2.SDL::SDL_HapticSetAutocenter", SDL_HapticSetAutocenter);
    add_call("SDL2.SDL::SDL_HapticSetGain", SDL_HapticSetGain);
    add_call("SDL2.SDL::SDL_HapticStopAll", SDL_HapticStopAll);
    add_call("SDL2.SDL::SDL_HapticStopEffect", SDL_HapticStopEffect);
    add_call("SDL2.SDL::SDL_HapticUnpause", SDL_HapticUnpause);
    add_call("SDL2.SDL::SDL_HapticUpdateEffect", SDL_HapticUpdateEffect);
    add_call("SDL2.SDL::SDL_JoystickIsHaptic", SDL_JoystickIsHaptic);
    add_call("SDL2.SDL::SDL_MouseIsHaptic", SDL_MouseIsHaptic);
    add_call("SDL2.SDL::SDL_NumHaptics", SDL_NumHaptics);
    add_call("SDL2.SDL::SDL_NumSensors", SDL_NumSensors);
    add_call("SDL2.SDL::SDL_SensorGetDeviceType", SDL_SensorGetDeviceType);
    add_call("SDL2.SDL::SDL_SensorGetDeviceNonPortableType", SDL_SensorGetDeviceNonPortableType);
    add_call("SDL2.SDL::SDL_SensorGetDeviceInstanceID", SDL_SensorGetDeviceInstanceID);
    add_call("SDL2.SDL::SDL_SensorOpen", SDL_SensorOpen);
    add_call("SDL2.SDL::SDL_SensorFromInstanceID", SDL_SensorFromInstanceID);
    add_call("SDL2.SDL::SDL_SensorGetType", SDL_SensorGetType);
    add_call("SDL2.SDL::SDL_SensorGetNonPortableType", SDL_SensorGetNonPortableType);
    add_call("SDL2.SDL::SDL_SensorGetInstanceID", SDL_SensorGetInstanceID);
    add_call("SDL2.SDL::SDL_SensorGetData", SDL_SensorGetData);
    add_call("SDL2.SDL::SDL_SensorClose", SDL_SensorClose);
    add_call("SDL2.SDL::SDL_SensorUpdate", SDL_SensorUpdate);
    add_call("SDL2.SDL::SDL_AudioQuit", SDL_AudioQuit);
    add_call("SDL2.SDL::SDL_CloseAudio", SDL_CloseAudio);
    add_call("SDL2.SDL::SDL_CloseAudioDevice", SDL_CloseAudioDevice);
    add_call("SDL2.SDL::SDL_FreeWAV", SDL_FreeWAV);
    add_call("SDL2.SDL::SDL_GetAudioDeviceStatus", SDL_GetAudioDeviceStatus);
    add_call("SDL2.SDL::SDL_GetAudioStatus", SDL_GetAudioStatus);
    add_call("SDL2.SDL::SDL_GetNumAudioDevices", SDL_GetNumAudioDevices);
    add_call("SDL2.SDL::SDL_GetNumAudioDrivers", SDL_GetNumAudioDrivers);
    add_call("SDL2.SDL::SDL_LockAudio", SDL_LockAudio);
    add_call("SDL2.SDL::SDL_LockAudioDevice", SDL_LockAudioDevice);
    add_call("SDL2.SDL::SDL_OpenAudio", SDL_OpenAudio);
    add_call("SDL2.SDL::SDL_OpenAudio", SDL_OpenAudio);
    add_call("SDL2.SDL::SDL_PauseAudio", SDL_PauseAudio);
    add_call("SDL2.SDL::SDL_PauseAudioDevice", SDL_PauseAudioDevice);
    add_call("SDL2.SDL::SDL_UnlockAudio", SDL_UnlockAudio);
    add_call("SDL2.SDL::SDL_UnlockAudioDevice", SDL_UnlockAudioDevice);
    add_call("SDL2.SDL::SDL_QueueAudio", SDL_QueueAudio);
    add_call("SDL2.SDL::SDL_DequeueAudio", SDL_DequeueAudio);
    add_call("SDL2.SDL::SDL_GetQueuedAudioSize", SDL_GetQueuedAudioSize);
    add_call("SDL2.SDL::SDL_ClearQueuedAudio", SDL_ClearQueuedAudio);
    add_call("SDL2.SDL::SDL_NewAudioStream", SDL_NewAudioStream);
    add_call("SDL2.SDL::SDL_AudioStreamPut", SDL_AudioStreamPut);
    add_call("SDL2.SDL::SDL_AudioStreamGet", SDL_AudioStreamGet);
    add_call("SDL2.SDL::SDL_AudioStreamAvailable", SDL_AudioStreamAvailable);
    add_call("SDL2.SDL::SDL_AudioStreamClear", SDL_AudioStreamClear);
    add_call("SDL2.SDL::SDL_FreeAudioStream", SDL_FreeAudioStream);
    add_call("SDL2.SDL::SDL_Delay", SDL_Delay);
    add_call("SDL2.SDL::SDL_GetTicks", SDL_GetTicks);
    add_call("SDL2.SDL::SDL_GetPerformanceCounter", SDL_GetPerformanceCounter);
    add_call("SDL2.SDL::SDL_GetPerformanceFrequency", SDL_GetPerformanceFrequency);
    add_call("SDL2.SDL::SDL_AddTimer", SDL_AddTimer);
    add_call("SDL2.SDL::SDL_RemoveTimer", SDL_RemoveTimer);
    add_call("SDL2.SDL::SDL_SetWindowsMessageHook", NotImplemented);
    add_call("SDL2.SDL::SDL_iPhoneSetAnimationCallback", NotImplemented);
    add_call("SDL2.SDL::SDL_iPhoneSetEventPump", NotImplemented);
    add_call("SDL2.SDL::SDL_AndroidGetJNIEnv", NotImplemented);
    add_call("SDL2.SDL::SDL_AndroidGetActivity", NotImplemented);
    add_call("SDL2.SDL::SDL_IsAndroidTV", NotImplemented);
    add_call("SDL2.SDL::SDL_IsChromebook", NotImplemented);
    add_call("SDL2.SDL::SDL_IsDeXMode", NotImplemented);
    add_call("SDL2.SDL::SDL_AndroidBackButton", NotImplemented);
    add_call("SDL2.SDL::SDL_AndroidGetExternalStorageState", NotImplemented);
    add_call("SDL2.SDL::INTERNAL_SDL_AndroidGetExternalStoragePath", NotImplemented);
    add_call("SDL2.SDL::SDL_WinRTGetDeviceFamily", NotImplemented);
    add_call("SDL2.SDL::SDL_IsTablet", SDL_IsTablet);
    add_call("SDL2.SDL::SDL_GetWindowWMInfo", NotImplemented);
    add_call("SDL2.SDL::SDL_GetPowerInfo", SDL_GetPowerInfo);
    add_call("SDL2.SDL::SDL_GetCPUCount", SDL_GetCPUCount);
    add_call("SDL2.SDL::SDL_GetSystemRAM", SDL_GetSystemRAM);
    add_call("SDL2.SDL::INTERNAL_SDL_ShowMessageBox", SDL_ShowMessageBox);
    add_call("SDL2.SDL::SDL_GetWindowGammaRamp", SDL_GetWindowGammaRamp);
    add_call("SDL2.SDL::SDL_SetWindowGammaRamp", SDL_SetWindowGammaRamp);
    add_call("SDL2.SDL::SDL_CalculateGammaRamp", SDL_CalculateGammaRamp);
    add_call("SDL2.SDL::SDL_MixAudio", SDL_MixAudio);
    add_call("SDL2.SDL::SDL_MixAudioFormat", SDL_MixAudioFormat);
    
    add_call("SDL2.SDL_image::IMG_Init", IMG_Init);
    add_call("SDL2.SDL_image::IMG_Quit", IMG_Quit);
    add_call("SDL2.SDL_image::IMG_Load_RW", IMG_Load_RW);
    add_call("SDL2.SDL_image::IMG_LoadTexture_RW", IMG_LoadTexture_RW);
    add_call("SDL2.SDL_image::IMG_SavePNG_RW", IMG_SavePNG_RW);
    add_call("SDL2.SDL_image::IMG_SaveJPG_RW", IMG_SaveJPG_RW);
    
    add_call("SDL2.SDL_image::INTERNAL_IMG_Linked_Version", IMG_Linked_Version);
    add_call("SDL2.SDL_image::INTERNAL_IMG_Load", IMG_Load);
    add_call("SDL2.SDL_image::INTERNAL_IMG_LoadTyped_RW", IMG_LoadTyped_RW);
    add_call("SDL2.SDL_image::INTERNAL_IMG_LoadTexture", IMG_LoadTexture);
    add_call("SDL2.SDL_image::INTERNAL_IMG_LoadTextureTyped_RW", IMG_LoadTextureTyped_RW);
    add_call("SDL2.SDL_image::INTERNAL_IMG_SavePNG", IMG_SavePNG);
}